<script setup>
import { ref, watch } from 'vue';
import { Search, UserPlus, ShieldCheck } from '@lucide/vue';
import { dateTime } from '../format.js';
import { request } from '../api.js';
import { useAuth } from '../stores/auth.js';
import ErrorNotice from './ErrorNotice.vue';
import AppDialog from './AppDialog.vue';
const props = defineProps({ spaceId: { type: String, required: true } });
const auth = useAuth(), members = ref([]), candidates = ref([]), q = ref(''), revision = ref(1), error = ref(null), busy = ref(false), change = ref(null);
let epoch = 0;
async function load() { const own = ++epoch; error.value = null; candidates.value = []; try { const data = await request(`/spaces/${props.spaceId}/members`); if (own !== epoch) return; members.value = data.items; revision.value = data.row_version; } catch (cause) { if (own === epoch) error.value = cause; } }
async function search() { const own = epoch; error.value = null; try { const data = await request(`/spaces/${props.spaceId}/member-candidates?q=${encodeURIComponent(q.value.trim())}`); if (own === epoch) candidates.value = data.filter(u => !members.value.some(m => m.user_id === u.id)); } catch (cause) { if (own === epoch) error.value = cause; } }
async function save() { busy.value = true; error.value = null; try { await request(`/spaces/${props.spaceId}/members`, { method: 'PUT', headers: { 'If-Match': String(revision.value) }, body: JSON.stringify({ changes: [{ user_id: change.value.id, role: change.value.role }] }) }); change.value = null; await load(); } catch (cause) { error.value = cause; } finally { busy.value = false; } }
watch(() => props.spaceId, () => { q.value = ''; change.value = null; load(); }, { immediate: true });
</script>
<template><section class="panel account-panel"><h2>知识库成员</h2><p class="muted">{{ auth.isSuper ? '为已有账号分配本库的管理或问答权限。总管理员自动拥有所有库权限。' : '你可以为已有账号分配问答权限。其他知识库管理员由总管理员任命。' }}</p><form class="member-add" @submit.prevent="search"><label class="small muted">添加成员<input v-model="q" minlength="2" maxlength="100" required placeholder="输入至少 2 个字符搜索账号或姓名" aria-label="搜索可添加的成员"/></label><button class="btn" :disabled="q.trim().length < 2"><Search :size="16"/>查找账号</button></form><div v-if="candidates.length" class="member-candidates"><div v-for="user in candidates" :key="user.id"><span>{{ user.display_name }}<small class="account-row-details">{{ user.username }}</small></span><button class="btn small" @click="change = { id: user.id, name: user.display_name, role: 'qa' }"><UserPlus :size="15"/>添加</button></div></div><ErrorNotice :error="error" retry @retry="load"/><div class="table-scroll"><table class="data-table"><thead><tr><th>成员</th><th>本库权限</th><th>状态</th><th>分配时间</th><th>操作</th></tr></thead><tbody><tr v-for="member in members" :key="member.user_id"><td>{{ member.display_name }}<small class="account-row-details">{{ member.username }}</small></td><td>{{ member.role === 'manager' ? '知识库管理员' : '仅问答' }}</td><td>{{ member.enabled ? '已启用' : '已停用' }}</td><td class="small nowrap">{{ dateTime(member.created_at) }}</td><td><button v-if="auth.isSuper || member.role !== 'manager'" class="btn small" @click="change = { id: member.user_id, name: member.display_name, role: member.role }">修改权限</button><span v-else class="small muted">由总管理员管理</span></td></tr></tbody></table></div><p v-if="!members.length" class="muted small">尚未添加成员。</p></section><AppDialog :open="!!change" :title="`设置本库权限 · ${change?.name || ''}`" @close="!busy && (change = null)"><label class="field-label">本库权限</label><select v-if="change" v-model="change.role"><option value="none">无权限 · 移出本库</option><option value="qa">仅问答</option><option v-if="auth.isSuper" value="manager">知识库管理员</option></select><p class="auth-message">移出后，该账号将不能继续问答或查看本库的旧会话和引用。</p><ErrorNotice :error="error"/><div class="dialog-actions"><button class="btn" :disabled="busy" @click="change = null">取消</button><button class="btn primary" :disabled="busy" @click="save">确认保存</button></div></AppDialog></template>
