<script setup>
import { computed, ref, watch } from 'vue';
const props = defineProps({ asset: Object, busy: Boolean });
const emit = defineEmits(['save', 'cancel']);
const draft = ref(null), reason = ref(''), confirmed = ref(false);
watch(() => props.asset.id, () => { draft.value = JSON.parse(JSON.stringify(props.asset.extraction)); reason.value = ''; confirmed.value = false; }, { immediate: true });
const changed = computed(() => JSON.stringify(draft.value) !== JSON.stringify(props.asset.extraction));
const editableCells = table => [...table.cells].sort((a,b) => a.row - b.row || a.column - b.column);
function save() { if (changed.value && confirmed.value && reason.value.trim()) emit('save', { extraction: draft.value, reason: reason.value.trim() }); }
</script>
<template><form class="visual-editor" @submit.prevent="save"><div class="section-toolbar"><div><h3>对照原图修订</h3><p class="small muted">保留原始识别记录；修改将生成新版本，复核发布后生效。</p></div><button type="button" class="btn" @click="emit('cancel')">取消修订</button></div>
  <template v-if="draft"><div v-for="(table, ti) in draft.tables" :key="ti" class="editor-table"><h4>{{ table.title || `表格 ${ti + 1}` }}</h4><div class="visual-table"><table><thead><tr><th>位置</th><th>原内容</th><th>修订内容</th></tr></thead><tbody><tr v-for="cell in editableCells(table)" :key="`${cell.row}-${cell.column}`"><td>第 {{ cell.row + 1 }} 行 / 第 {{ cell.column + 1 }} 列</td><td>{{ asset.extraction.tables[ti].cells.find(c => c.row === cell.row && c.column === cell.column)?.text }}</td><td><input v-model="cell.text" :aria-label="`表格 ${ti + 1} 第 ${cell.row + 1} 行第 ${cell.column + 1} 列`"/></td></tr></tbody></table></div><label v-for="(_, ni) in table.notes" :key="ni" class="field-label">条件 / 注释 {{ ni + 1 }}<textarea v-model="table.notes[ni]"/></label></div>
  <div v-for="(graph, gi) in draft.graphs" :key="gi" class="editor-graph"><h4>关系图 {{ gi + 1 }}</h4><label v-for="node in graph.nodes" :key="node.id" class="field-label">节点名称<input v-model="node.label" :aria-label="`图 ${gi + 1} 节点 ${node.id}`"/></label><div v-for="(edge, ei) in graph.edges" :key="ei" class="edge-editor"><span class="small">连线 {{ ei + 1 }}</span><label>起点<select v-model="edge.source"><option v-for="n in [...graph.nodes, ...graph.groups]" :key="n.id" :value="n.id">{{ n.label || '未命名节点' }}</option></select></label><label>方向<select v-model="edge.direction"><option value="forward">起点 → 终点</option><option value="both">双向 ↔</option><option value="none">无箭头 —</option></select></label><label>终点<select v-model="edge.target"><option v-for="n in [...graph.nodes, ...graph.groups]" :key="n.id" :value="n.id">{{ n.label || '未命名节点' }}</option></select></label><label>线型<select v-model="edge.style"><option value="solid">实线</option><option value="dashed">虚线</option></select></label><label>连线条件<input v-model="edge.label"/></label></div></div>
  <p v-if="draft.tables.length || draft.graphs.length" class="small muted">修改表格或关系后会同步重建提取文字，清除未更新的自动说明；图外条件请保留在正文 / 图注中。</p><label class="field-label">可见内容说明<textarea v-model="draft.description" rows="4"/></label>
  <label v-if="!draft.tables.length && !draft.graphs.length" class="field-label">提取文字<textarea v-model="draft.transcription" rows="5"/></label><div v-if="draft.uncertainties?.length || draft.graphs.some(g=>g.uncertainties.length)" class="notice warning"><div><p>原识别仍有不确定项；必须逐项对照原图解决后才能提交。</p><ul><li v-for="item in [...draft.uncertainties, ...draft.graphs.flatMap(g=>g.uncertainties)]" :key="item">{{ item }}</li></ul><button type="button" class="btn" @click="draft.uncertainties=[]; draft.graphs.forEach(g=>g.uncertainties=[])">我已逐项修正并确认这些问题</button></div></div><label class="field-label">正文 / 图注<textarea v-model="draft.body_text" rows="3"/></label><label class="field-label">修订原因<textarea v-model="reason" rows="2" required maxlength="2000" placeholder="例如：第 3 行工作功率应为 323 W，已对照原图确认。"/></label><label class="check-row"><input v-model="confirmed" type="checkbox"/>我已对照原图确认这些修改；我也已确认整张图片其余内容；原图无法证明的内容没有补填。</label><button class="btn primary" :disabled="busy || !changed || !confirmed || !reason.trim() || draft.uncertainties?.length || draft.graphs.some(g=>g.uncertainties.length)">{{ busy ? '正在提交…' : '确认修订并生成新版本' }}</button></template>
</form></template>
