<script setup>
import { computed, ref, watch, nextTick } from 'vue';
import DOMPurify from 'dompurify';
import { sourceUrl } from '../api.js';
import { locationLabel, visualIssueMessage } from '../format.js';
import MermaidDiagram from './MermaidDiagram.vue';
import MarkdownContent from './MarkdownContent.vue';
const props = defineProps({ asset: { type: Object, required: true }, compact: Boolean, viewKey: String, reviewable:Boolean });
const emit=defineEmits(['review-issue']);
const tab = ref('result'), zoom = ref(100), imageFailed = ref(false), imageHost = ref(null), resultHost = ref(null), selected = ref([]), focusNotice = ref('');
const sourceBox=ref(null);
const issueGroups=computed(()=>[{key:'blocking',label:'阻止使用：确定冲突或结构问题'},{key:'review',label:'需要人工核对'},{key:'info',label:'识别说明'}].map(g=>({...g,items:(props.asset.review_issues || (props.asset.issues || []).map(message=>({message,severity:'review'}))).filter(i=>(i.severity || 'review')===g.key)})).filter(g=>g.items.length));
const partial=computed(()=>props.asset.graph_coverage?.some(g=>g.partial) || (props.asset.extraction?.graphs || []).some(g=>[...g.groups,...g.nodes,...g.edges].some(x=>['excluded','pending'].includes(x.review_status))));
const stateKey = computed(() => `visual-view.${props.viewKey || props.asset.id}`);
const imageUrl = computed(() => sourceUrl(props.asset.image_url + ((props.asset.coordinate_space || sourceBox.value || (props.asset.extraction?.graphs || []).some(g=>[...g.nodes,...g.groups,...g.edges].some(x=>x.bbox && ['human','ocr'].includes(x.bbox_basis)))) ? '?normalized=true' : '')));
const regions = computed(() => sourceBox.value ? [{id:'source-object',bbox:sourceBox.value,text:'已核实原图区域'}] : (props.asset.regions || []).filter(r => selected.value.includes(r.id)));
function saveView() { sessionStorage.setItem(stateKey.value, JSON.stringify({ tab:tab.value, zoom:zoom.value, top:imageHost.value?.scrollTop || 0, left:imageHost.value?.scrollLeft || 0, resultTop:resultHost.value?.scrollTop || 0 })); }
watch([tab, zoom], saveView);
async function restoreView() { let state; try { state = JSON.parse(sessionStorage.getItem(stateKey.value) || '{}'); } catch { state = {}; }
 tab.value = state.tab || 'result'; zoom.value = state.zoom || 100; imageFailed.value = false; selected.value = props.asset.focus_region_ids || []; focusNotice.value = ''; sourceBox.value=null; await nextTick();
 if (imageHost.value) { imageHost.value.scrollTop = state.top || 0; imageHost.value.scrollLeft = state.left || 0; } if (resultHost.value) resultHost.value.scrollTop = state.resultTop || 0;
}
function focusTarget(target) { selected.value = target?.region_ids || []; sourceBox.value=['human','ocr'].includes(target?.bbox_basis) ? target.bbox : null; focusNotice.value = sourceBox.value ? (target.bbox_basis==='human'?'已框出人工对照原图确认的区域。':'已框出独立 OCR 核实的原图区域。') : selected.value.length ? '已框出独立 OCR 确认的文字区域。' : '此处暂不能唯一定位，请对照整张原图；不会猜测单元格或箭头位置。'; nextTick(() => imageHost.value?.querySelector('.visual-region')?.scrollIntoView?.({ block:'nearest', inline:'nearest', behavior:'smooth' })); }
function focusCell(event, table) { const cell = event.target.closest('td,th'); if (!cell) return; const row = cell.parentElement.rowIndex, cells = (props.asset.extraction.tables[table]?.cells || []).filter(c => c.row === row).sort((a,b) => a.column-b.column); const source = cells[cell.cellIndex]; focusTarget((props.asset.local_check?.targets || []).find(t=>t.kind==='cell' && t.table===table && t.row===row && t.column===source?.column)); }
function focusNode(graph, nodeId) { const node=props.asset.extraction.graphs[graph].nodes.find(n=>n.id===nodeId); focusTarget(node?.bbox_basis==='human' ? node : (props.asset.local_check?.targets || []).find(t=>t.kind==='node' && t.graph===graph && t.node_id===nodeId)); }
function focusEdge(graph,index) { const edge=props.asset.extraction.graphs[graph].edges[index]; focusTarget(edge?.bbox_basis==='human' ? edge : (props.asset.local_check?.targets || []).find(t=>t.kind==='edge' && t.graph===graph && t.edge_index===index)); }
function focusGroup(graph,group) { focusTarget(group.bbox_basis==='human' ? group : (props.asset.local_check?.targets || []).find(t=>t.kind==='group' && t.graph===graph && t.group_id===group.id)); }
watch(() => stateKey.value, restoreView, { immediate:true });
const kinds = { diagram: '关系图 / 流程图', table: '表格', photo: '照片', chart: '统计图', text: '文字图片', mixed: '混合内容', unknown: '类型待确认' };
const tables = computed(() => (props.asset.table_html || []).map(html => DOMPurify.sanitize(html, { ALLOWED_TAGS: ['table','tbody','thead','tr','td','th'], ALLOWED_ATTR: ['rowspan','colspan'] })));

</script>
<template><article :class="['visual-asset', { compact }]"><header class="visual-asset-heading"><div><strong>{{ asset.extraction?.title || '文档图片' }}</strong><p class="small muted">{{ kinds[asset.extraction?.kind] || '识别未完成' }} · {{ locationLabel(asset.locator) || asset.locator?.part }}</p><p v-if="asset.section_path && asset.section_path !== 'root'" class="small muted">所属章节：{{ asset.section_path }}</p><p v-if="asset.caption" class="small muted">图注：{{ asset.caption }}</p></div><span :class="['visual-status', asset.status === 'verified' ? 'verified' : 'pending']">{{ asset.status === 'verified' ? (partial ? '部分内容已确认' : asset.origin === 'human_review' ? '人工复核通过' : '原图核对通过') : asset.status === 'excluded' ? '已排除' : asset.status === 'failed' ? '识别失败' : '待复核' }}</span></header>
  <div v-if="asset.status !== 'verified'" class="notice warning"><div><strong>这张图片尚不能作为问答依据</strong><p>共 {{ asset.review_issues?.length || asset.issues?.length || 0 }} 项需要核对。只有保留内容通过复核后才能进入问答。</p><details class="visual-issue-list"><summary>查看问题及逐项处理</summary><section v-for="group in issueGroups" :key="group.key"><h4>{{ group.label }} · {{ group.items.length }} 项</h4><ul><li v-for="(issue,index) in group.items" :key="issue.id || index">{{ visualIssueMessage(issue.message) }} <button v-if="reviewable && asset.extraction && group.key!=='info'" class="btn small-button" @click="emit('review-issue',issue.id || null)">处理此问题</button></li></ul></section></details><p>可重新识别；仍看不清的内容需要补充清晰原图或修订文档。</p></div></div>
  <div v-if="partial && asset.status==='verified'" class="notice warning"><div><strong>部分内容可用于问答</strong><p>已排除或未确认的节点与连线不能作为回答依据。下方结构图只展示已确认范围；原图仍保留完整内容，不能据此推断被排除的路径。</p></div></div>
  <details v-if="asset.history?.length" class="visual-review-history"><summary>人工复核记录 · {{ asset.history.length }} 次</summary><section v-for="(entry,i) in asset.history" :key="i"><p><strong>{{ entry.reason }}</strong></p><p class="small muted">{{ entry.at?new Date(entry.at*1000).toLocaleString('zh-CN'):'历史复核' }} · {{ entry.changes?.length || 0 }} 处变化</p><ul v-if="entry.resolutions?.length"><li v-for="item in entry.resolutions" :key="item.issue_id">{{ {corrected:'已修正',confirmed:'核实正确',excluded:'明确排除'}[item.disposition] }}：{{ item.reason }}</li></ul><p v-else class="small muted">此条为旧版审核记录，未保存逐项问题的处置明细。</p></section></details>
  <div class="visual-comparison"><section class="visual-original"><div class="visual-pane-heading"><strong>原图</strong><div class="visual-actions"><button class="icon-button" aria-label="缩小原图" :disabled="zoom <= 50" @click="zoom -= 25">−</button><span class="small">{{ zoom }}%</span><button class="icon-button" aria-label="放大原图" :disabled="zoom >= 300" @click="zoom += 25">＋</button><button class="btn small-button" @click="zoom = 100">适应</button></div></div><div ref="imageHost" class="visual-image-scroll" @scroll.passive="saveView"><p v-if="imageFailed" class="notice warning">原图暂不可预览，请下载原文档查看。</p><div v-else class="visual-image-canvas" :style="{ width: zoom + '%' }"><img :key="asset.id" :src="imageUrl" :alt="asset.extraction?.title || '文档中的原始图片'" style="width:100%;max-width:none" loading="lazy" @error="imageFailed = true"/><span v-for="region in regions" :key="region.id" class="visual-region" :title="region.text" :style="{ left:region.bbox[0]*100+'%', top:region.bbox[1]*100+'%', width:(region.bbox[2]-region.bbox[0])*100+'%', height:(region.bbox[3]-region.bbox[1])*100+'%' }"/></div></div><p v-if="focusNotice" class="small visual-focus-note">{{ focusNotice }}</p></section>
  <section class="visual-extracted"><div class="visual-pane-heading"><strong>识别结果</strong><div class="visual-tabs"><button :class="{ active: tab === 'result' }" @click="tab = 'result'">结构展示</button><button :class="{ active: tab === 'text' }" @click="tab = 'text'">提取文字</button></div></div><div ref="resultHost" class="visual-result-body" @scroll.passive="saveView"><p v-if="!asset.extraction" class="muted">没有可用的识别结果。</p><template v-else-if="tab === 'result'"><MarkdownContent v-if="asset.extraction.description" :text="asset.extraction.description"/><MermaidDiagram v-for="(code,i) in asset.mermaid || []" :key="asset.id + '-' + i" :code="code"/><div v-for="(html,i) in tables" :key="i"><div class="visual-table" @click="focusCell($event,i)" v-html="html"/><p v-for="(note,n) in asset.extraction.tables?.[i]?.notes || []" :key="n" class="small muted">{{ note }}</p></div><section v-if="asset.focus_targets?.length" class="visual-fact-targets"><h4>{{ asset.focus_targets.some(t=>t.usage==='answer')?'回答引用的事实位置':'该条引用包含的关系（点击定位）' }}</h4><p v-if="asset.focus_targets.some(t=>t.usage==='citation_candidate')" class="small muted">候选关系来自当前有效引用，点击后仅框出已核实原图区域；不表示回答使用了每条关系。</p><button v-for="target in asset.focus_targets" :key="target.fact_id" class="btn small-button" @click="focusTarget(target)">{{ target.text }}</button></section><div v-for="(graph,g) in asset.extraction.graphs || []" :key="g" class="visual-node-targets"><button v-for="(node,ni) in graph.nodes" :key="node.id" class="btn small-button" @click="focusNode(g,node.id)">定位 {{ node.label?.trim() || `无可见文字节点 ${ni+1}` }}{{ node.review_status==='excluded'?'（已排除）':node.review_status==='pending'?'（待确认）':'' }}</button><button v-for="group in graph.groups" :key="group.id" class="btn small-button" @click="focusGroup(g,group)">定位分组 {{ group.label || '无可见标题' }}{{ group.review_status==='excluded'?'（已排除）':group.review_status==='pending'?'（待确认）':'' }}</button><button v-for="(edge,ei) in graph.edges" :key="ei" class="btn small-button" @click="focusEdge(g,ei)">定位连线 {{ ei+1 }}{{ edge.review_status==='excluded'?'（已排除）':'' }}</button></div><MarkdownContent v-if="asset.extraction.body_text" :text="asset.extraction.body_text"/><p v-if="!asset.mermaid?.length && !tables.length" class="visual-transcription">{{ asset.extraction.transcription }}</p></template><pre v-else class="visual-transcription">{{ asset.extraction.transcription || '图中没有可读取的文字。' }}</pre></div></section></div>
</article></template>
