<script setup>
import { computed, ref, watch, nextTick } from 'vue';
import DOMPurify from 'dompurify';
import { sourceUrl } from '../api.js';
import { locationLabel, visualIssueMessage } from '../format.js';
import MermaidDiagram from './MermaidDiagram.vue';
import MarkdownContent from './MarkdownContent.vue';
const props = defineProps({ asset: { type: Object, required: true }, compact: Boolean, viewKey: String });
const tab = ref('result'), zoom = ref(100), imageFailed = ref(false), imageHost = ref(null), resultHost = ref(null), selected = ref([]), focusNotice = ref('');
const stateKey = computed(() => `visual-view.${props.viewKey || props.asset.id}`);
const imageUrl = computed(() => sourceUrl(props.asset.image_url + (props.asset.coordinate_space ? '?normalized=true' : '')));
const regions = computed(() => (props.asset.regions || []).filter(r => selected.value.includes(r.id)));
function saveView() { sessionStorage.setItem(stateKey.value, JSON.stringify({ tab:tab.value, zoom:zoom.value, top:imageHost.value?.scrollTop || 0, left:imageHost.value?.scrollLeft || 0, resultTop:resultHost.value?.scrollTop || 0 })); }
watch([tab, zoom], saveView);
async function restoreView() { let state; try { state = JSON.parse(sessionStorage.getItem(stateKey.value) || '{}'); } catch { state = {}; }
 tab.value = state.tab || 'result'; zoom.value = state.zoom || 100; imageFailed.value = false; selected.value = props.asset.focus_region_ids || []; focusNotice.value = ''; await nextTick();
 if (imageHost.value) { imageHost.value.scrollTop = state.top || 0; imageHost.value.scrollLeft = state.left || 0; } if (resultHost.value) resultHost.value.scrollTop = state.resultTop || 0;
}
function focusTarget(target) { selected.value = target?.region_ids || []; focusNotice.value = selected.value.length ? '已框出独立 OCR 确认的文字区域。' : '此处暂不能唯一定位，请对照整张原图；不会猜测单元格或箭头位置。'; nextTick(() => imageHost.value?.querySelector('.visual-region')?.scrollIntoView?.({ block:'nearest', inline:'nearest', behavior:'smooth' })); }
function focusCell(event, table) { const cell = event.target.closest('td,th'); if (!cell) return; const row = cell.parentElement.rowIndex, cells = (props.asset.extraction.tables[table]?.cells || []).filter(c => c.row === row).sort((a,b) => a.column-b.column); const source = cells[cell.cellIndex]; focusTarget((props.asset.local_check?.targets || []).find(t=>t.kind==='cell' && t.table===table && t.row===row && t.column===source?.column)); }
function focusNode(graph, nodeId) { focusTarget((props.asset.local_check?.targets || []).find(t=>t.kind==='node' && t.graph===graph && t.node_id===nodeId)); }
watch(() => stateKey.value, restoreView, { immediate:true });
const kinds = { diagram: '关系图 / 流程图', table: '表格', photo: '照片', chart: '统计图', text: '文字图片', mixed: '混合内容', unknown: '类型待确认' };
const tables = computed(() => (props.asset.table_html || []).map(html => DOMPurify.sanitize(html, { ALLOWED_TAGS: ['table','tbody','thead','tr','td','th'], ALLOWED_ATTR: ['rowspan','colspan'] })));

</script>
<template><article :class="['visual-asset', { compact }]"><header class="visual-asset-heading"><div><strong>{{ asset.extraction?.title || '文档图片' }}</strong><p class="small muted">{{ kinds[asset.extraction?.kind] || '识别未完成' }} · {{ locationLabel(asset.locator) || asset.locator?.part }}</p><p v-if="asset.section_path && asset.section_path !== 'root'" class="small muted">所属章节：{{ asset.section_path }}</p><p v-if="asset.caption" class="small muted">图注：{{ asset.caption }}</p></div><span :class="['visual-status', asset.status === 'verified' ? 'verified' : 'pending']">{{ asset.status === 'verified' ? (asset.origin === 'human_review' ? '人工复核通过' : '原图核对通过') : asset.status === 'excluded' ? '已排除' : asset.status === 'failed' ? '识别失败' : '待复核' }}</span></header>
  <div v-if="asset.status !== 'verified'" class="notice warning"><div><strong>这张图片尚不能作为问答依据</strong><ul><li v-for="issue in asset.issues" :key="issue">{{ visualIssueMessage(issue) }}</li></ul><p>可重新识别；仍看不清的内容需要补充清晰原图或修订文档。</p></div></div>
  <div class="visual-comparison"><section class="visual-original"><div class="visual-pane-heading"><strong>原图</strong><div class="visual-actions"><button class="icon-button" aria-label="缩小原图" :disabled="zoom <= 50" @click="zoom -= 25">−</button><span class="small">{{ zoom }}%</span><button class="icon-button" aria-label="放大原图" :disabled="zoom >= 300" @click="zoom += 25">＋</button><button class="btn small-button" @click="zoom = 100">适应</button></div></div><div ref="imageHost" class="visual-image-scroll" @scroll.passive="saveView"><p v-if="imageFailed" class="notice warning">原图暂不可预览，请下载原文档查看。</p><div v-else class="visual-image-canvas" :style="{ width: zoom + '%' }"><img :key="asset.id" :src="imageUrl" :alt="asset.extraction?.title || '文档中的原始图片'" style="width:100%;max-width:none" loading="lazy" @error="imageFailed = true"/><span v-for="region in regions" :key="region.id" class="visual-region" :title="region.text" :style="{ left:region.bbox[0]*100+'%', top:region.bbox[1]*100+'%', width:(region.bbox[2]-region.bbox[0])*100+'%', height:(region.bbox[3]-region.bbox[1])*100+'%' }"/></div></div><p v-if="focusNotice" class="small visual-focus-note">{{ focusNotice }}</p></section>
  <section class="visual-extracted"><div class="visual-pane-heading"><strong>识别结果</strong><div class="visual-tabs"><button :class="{ active: tab === 'result' }" @click="tab = 'result'">结构展示</button><button :class="{ active: tab === 'text' }" @click="tab = 'text'">提取文字</button></div></div><div ref="resultHost" class="visual-result-body" @scroll.passive="saveView"><p v-if="!asset.extraction" class="muted">没有可用的识别结果。</p><template v-else-if="tab === 'result'"><MarkdownContent v-if="asset.extraction.description" :text="asset.extraction.description"/><MermaidDiagram v-for="(code,i) in asset.mermaid || []" :key="asset.id + '-' + i" :code="code"/><div v-for="(html,i) in tables" :key="i"><div class="visual-table" @click="focusCell($event,i)" v-html="html"/><p v-for="(note,n) in asset.extraction.tables?.[i]?.notes || []" :key="n" class="small muted">{{ note }}</p></div><div v-for="(graph,g) in asset.extraction.graphs || []" :key="g" class="visual-node-targets"><button v-for="node in graph.nodes" :key="node.id" class="btn small-button" @click="focusNode(g,node.id)">定位 {{ node.label }}</button><button v-if="graph.edges.length" class="btn small-button" @click="focusTarget(null)">核对箭头位置</button></div><MarkdownContent v-if="asset.extraction.body_text" :text="asset.extraction.body_text"/><p v-if="!asset.mermaid?.length && !tables.length" class="visual-transcription">{{ asset.extraction.transcription }}</p></template><pre v-else class="visual-transcription">{{ asset.extraction.transcription || '图中没有可读取的文字。' }}</pre></div></section></div>
</article></template>
