"""Storage port for directory manifests and recoverable upload intents."""

from collections.abc import Sequence
from contextlib import AbstractContextManager
from pathlib import Path
from typing import Any, Protocol


class DirectorySyncLedgerPort(Protocol):
    path: Path

    def get(self, key: str) -> dict[str, Any]: ...
    def get_many(self, keys: Sequence[str]) -> dict[str, dict[str, Any]]: ...
    def put(self, key: str, value: dict[str, Any]) -> None: ...
    def put_many(self, records: dict[str, dict[str, Any]]) -> None: ...
    def entries(self, prefix: str) -> dict[str, dict[str, Any]]: ...
    def snapshots(self, scope: str) -> Sequence[dict[str, Any]]: ...
    def lock(self, scope: str) -> AbstractContextManager[Any]: ...
