<script setup>
import { computed, onUnmounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ArrowLeft, Upload, Search, FileText, ChevronRight, RotateCw, SlidersHorizontal, ArrowUpRight, BookOpen, Check, LoaderCircle } from '@lucide/vue';
import { useWorkspace } from '../stores/workspace.js';
import { request, requestPage, queryString, confirmPublication, jobCommand } from '../api.js';
import { useResource } from '../composables/useResource.js';
import { dateTime, fileSize, locationLabel, availabilityLabels, processingLabels } from '../format.js';
import StatusBadge from '../components/StatusBadge.vue';
import ErrorNotice from '../components/ErrorNotice.vue';
import EmptyState from '../components/EmptyState.vue';
import UploadDialog from '../components/UploadDialog.vue';
import AppDialog from '../components/AppDialog.vue';
const route = useRoute(), router = useRouter(), store = useWorkspace();
const spaceId = computed(() => route.params.spaceId), view = computed(() => route.params.view || 'documents');
const space = computed(() => store.spaces.find(item => item.id === spaceId.value));
const q = ref(route.query.q || ''), availability = ref(route.query.availability || ''), processing = ref(route.query.processing || ''), sort = ref(route.query.sort || 'updated_desc');
const selected = ref([]), uploading = ref(false), batchBusy = ref(false), actionError = ref(null), publishOpen = ref(false), publishResults = ref([]);
const publishTargets = ref([]), qualityLoading = ref(false);
const rows = ref([]), cursor = ref(null), loadingMore = ref(false);
let listRevision = 0, filterTimer, refreshTimer;
const list = useResource(async (signal) => requestPage(`/spaces/${spaceId.value}/documents/preview?${queryString({ q: q.value, availability: availability.value, processing: processing.value, sort: sort.value, limit: 30 })}`, { signal }));
async function load() { const own = ++listRevision; selected.value = []; const data = await list.load(); if (data && own === listRevision) { rows.value = data.items; cursor.value = data.nextCursor; } }
async function more() {
  if (!cursor.value || loadingMore.value) return;
  const own = listRevision; loadingMore.value = true;
  try { const data = await requestPage(`/spaces/${spaceId.value}/documents/preview?${queryString({ q: q.value, availability: availability.value, processing: processing.value, sort: sort.value, cursor: cursor.value, limit: 30 })}`); if (own === listRevision) { rows.value.push(...data.items.filter(r => !rows.value.some(old => old.document_id === r.document_id))); cursor.value = data.nextCursor; } }
  catch (cause) { if (own === listRevision) actionError.value = cause; } finally { if (own === listRevision) loadingMore.value = false; }
}
function filterQuery() { return Object.fromEntries(Object.entries({ q: q.value, availability: availability.value, processing: processing.value, sort: sort.value === 'updated_desc' ? '' : sort.value }).filter(([, value]) => value)); }
watch([q, availability, processing, sort], () => { clearTimeout(filterTimer); filterTimer = setTimeout(() => { if (view.value === 'documents') { router.replace({ query: filterQuery() }); load(); } }, 250); });
watch(() => route.query, query => { q.value = String(query.q || ''); availability.value = String(query.availability || ''); processing.value = String(query.processing || ''); sort.value = String(query.sort || 'updated_desc'); });
watch(spaceId, () => { ++listRevision; list.clear(); rows.value = []; cursor.value = null; selected.value = []; q.value = route.query.q || ''; availability.value = route.query.availability || ''; processing.value = route.query.processing || ''; sort.value = route.query.sort || 'updated_desc'; loadingMore.value = false; uploading.value = false; load(); }, { immediate: true });
refreshTimer = setInterval(() => { if (view.value === 'documents' && rows.value.some(r => ['DRAFT', 'PROCESSING'].includes(r.processing_state)) && !selected.value.length && !cursor.value) load(); }, 5000);
onUnmounted(() => { clearInterval(refreshTimer); clearTimeout(filterTimer); });
const selectedRows = computed(() => rows.value.filter(row => selected.value.includes(row.document_id)));
function toggleAll(event) { selected.value = event.target.checked ? rows.value.map(row => row.document_id) : []; }
async function retrySelected() { batchBusy.value = true; actionError.value = null; try { for (const row of selectedRows.value.filter(r => r.available_actions.includes('retry'))) await jobCommand(row.job_id, 'retry'); await load(); } catch (cause) { actionError.value = cause; } finally { batchBusy.value = false; } }
async function preparePublication() {
  publishResults.value = []; publishTargets.value = selectedRows.value.filter(r => r.available_actions.includes('review_publish')).map(row => ({ ...row, quality: null, qualityError: null })); publishOpen.value = true; qualityLoading.value = true;
  await Promise.all(publishTargets.value.map(async row => { try { row.quality = await request(`/document-versions/${row.version_id}/quality-report`); } catch (error) { row.qualityError = error; } })); qualityLoading.value = false;
}
async function publishSelected() {
  batchBusy.value = true; publishResults.value = []; const targets = publishTargets.value.filter(r => r.quality && !r.qualityError && r.quality.disposition !== 'BLOCKED_REAL_VALIDATION');
  for (const row of targets) { try { const quality = await request(`/document-versions/${row.version_id}/quality-report`); if (quality.disposition === 'BLOCKED_REAL_VALIDATION') throw new Error('PUBLICATION_QUALITY_NOT_READY'); const result = await confirmPublication(row.version_id, '已查看质量后批量确认发布'); publishResults.value.push({ name: row.filename, success: result.phase === 'published', detail: result.error_code }); } catch (cause) { publishResults.value.push({ name: row.filename, success: false, detail: cause.message }); } }
  batchBusy.value = false; await Promise.all([load(), store.refresh()]);
}
const retrievalQuery = ref(''), topK = ref(10);
const retrieval = useResource(async (signal) => request('/search', { method: 'POST', signal, body: JSON.stringify({ query: retrievalQuery.value, space_id: spaceId.value, limit: topK.value }) }));
watch(spaceId, () => { retrieval.clear(); retrievalQuery.value = ''; });
const settingsName = ref(''), settingsDescription = ref(''), settingsBusy = ref(false), settingsSaved = ref(false);
watch(space, item => { settingsName.value = item?.name || ''; settingsDescription.value = item?.description || ''; settingsSaved.value = false; }, { immediate: true });
async function saveSettings() { settingsBusy.value = true; actionError.value = null; try { await request(`/spaces/${spaceId.value}`, { method: 'PATCH', body: JSON.stringify({ name: settingsName.value.trim(), description: settingsDescription.value.trim() }) }); await store.refresh(); settingsSaved.value = true; } catch (cause) { actionError.value = cause; } finally { settingsBusy.value = false; } }
</script>
<template><div class="page library-detail-page">
  <RouterLink to="/knowledge-bases" class="back-link"><ArrowLeft :size="15"/>全部知识库</RouterLink>
  <div class="page-heading compact"><div class="title-with-icon"><span class="library-symbol"><BookOpen :size="26"/></span><div><h1>{{ space?.name || '知识库' }}</h1><p class="page-description">{{ space?.description || '管理知识来源，检查每一份文档的问答可用状态。' }}</p></div></div><button class="btn primary" :disabled="!space" @click="uploading = true"><Upload :size="17"/>上传文档</button></div>
  <div class="inline-metrics"><span><strong>{{ space?.document_count ?? '—' }}</strong> 份文档</span><span><i class="dot success"/><strong>{{ space?.answerable_count ?? '—' }}</strong> 份可问答</span><span><i class="dot warning"/><strong>{{ space?.pending_count ?? '—' }}</strong> 份待处理</span><RouterLink :to="`/chat?space=${spaceId}`">在此知识库提问<ArrowUpRight :size="14"/></RouterLink></div>
  <nav class="tab-bar" aria-label="知识库页面"><RouterLink v-for="tab in [{ id: 'documents', label: '文档' }, { id: 'retrieval', label: '检索测试' }, { id: 'settings', label: '设置' }]" :key="tab.id" :to="`/knowledge-bases/${spaceId}/${tab.id}`" :class="{ active: view === tab.id }">{{ tab.label }}</RouterLink></nav>
  <ErrorNotice :error="actionError"/>
  <section v-if="view === 'documents'" class="panel document-panel">
    <div class="document-toolbar"><label class="search-field"><Search :size="16"/><input v-model="q" placeholder="搜索文档名称…" aria-label="搜索文档"/></label><div class="toolbar-actions"><select v-model="availability" aria-label="问答可用状态"><option value="">全部可用状态</option><option v-for="(label, value) in availabilityLabels" :key="value" :value="value" v-show="!['unknown', 'deleted'].includes(value)">{{ label }}</option></select><select v-model="processing" aria-label="解析状态"><option value="">全部解析状态</option><option v-for="key in ['PROCESSING', 'VALIDATED', 'FAILED', 'CANCELLED']" :key="key" :value="key">{{ processingLabels[key] }}</option></select><select v-model="sort" aria-label="文档排序"><option value="updated_desc">最近更新</option><option value="updated_asc">最早更新</option></select><button class="icon-button" aria-label="刷新文档" :disabled="list.loading.value" @click="load"><RotateCw :size="17" :class="{ spin: list.loading.value }"/></button></div></div>
    <div v-if="selected.length" class="batch-toolbar"><span>已选择 {{ selected.length }} 份文档</span><button class="btn small" :disabled="batchBusy || !selectedRows.some(r => r.available_actions.includes('review_publish'))" @click="preparePublication">检查并批量发布</button><button class="btn small" :disabled="batchBusy || !selectedRows.some(r => r.available_actions.includes('retry'))" @click="retrySelected">重试失败任务</button><button class="text-button" @click="selected = []">取消选择</button></div>
    <ErrorNotice :error="list.error.value" retry @retry="load"/>
    <div v-if="list.loading.value && !rows.length" class="table-skeleton"><div v-for="i in 5" :key="i"/></div>
    <div v-else-if="rows.length" class="table-scroll"><table class="data-table"><thead><tr><th class="checkbox-cell"><input type="checkbox" aria-label="选择本页全部文档" :checked="selected.length === rows.length" @change="toggleAll"/></th><th>文档名称</th><th>解析状态</th><th>问答可用状态</th><th>分块</th><th>更新时间</th><th/></tr></thead><tbody><tr v-for="row in rows" :key="row.document_id" :class="{ 'row-selected': selected.includes(row.document_id) }"><td class="checkbox-cell"><input v-model="selected" type="checkbox" :value="row.document_id" :aria-label="`选择 ${row.filename}`"/></td><td><RouterLink class="document-name" :to="`/knowledge-bases/${spaceId}/documents/${row.document_id}`"><span class="file-icon"><FileText :size="19"/></span><span><strong>{{ row.filename }}</strong><small>{{ fileSize(row.size_bytes) }}<span> · v{{ row.version_no }}</span></small></span></RouterLink></td><td><StatusBadge :value="row.processing_state" processing/></td><td><StatusBadge :value="row.availability"/><small v-if="row.availability === 'inconsistent'" class="cell-note">需要核对发布记录</small></td><td class="mono">{{ row.chunk_count }}</td><td class="small muted nowrap">{{ dateTime(row.updated_at) }}</td><td><RouterLink class="icon-button" :to="`/knowledge-bases/${spaceId}/documents/${row.document_id}`" :aria-label="`查看 ${row.filename}`"><ChevronRight :size="17"/></RouterLink></td></tr></tbody></table></div>
    <EmptyState v-else-if="!list.error.value" :title="q || availability || processing ? '没有符合条件的文档' : '这个知识库还没有文档'" :description="q || availability || processing ? '调整搜索或筛选条件，查看其他文档。' : '上传文件，自动完成解析与索引构建。'"><button v-if="!q && !availability && !processing" class="btn primary" @click="uploading = true"><Upload :size="16"/>上传文档</button></EmptyState>
    <footer v-if="rows.length" class="table-footer"><span>已显示 {{ rows.length }} 份文档 · 包含草稿与异常状态</span><button v-if="cursor" class="btn small" :disabled="loadingMore" @click="more">{{ loadingMore ? '加载中…' : '加载更多' }}</button></footer>
  </section>
  <section v-else-if="view === 'retrieval'" class="retrieval-layout"><div class="panel retrieval-controls"><span class="eyebrow">RETRIEVAL TEST</span><h2>检查知识如何被找到</h2><p class="muted">输入实际问题，查看命中片段与检索排序。本次测试不会生成答案。</p><label class="field-label" for="retrieval-query">测试问题</label><textarea id="retrieval-query" v-model="retrievalQuery" rows="5" maxlength="2000" placeholder="你希望从这些文档中找到什么？"/><label class="field-label" for="top-k">最多返回</label><select id="top-k" v-model.number="topK"><option :value="5">5 个片段</option><option :value="10">10 个片段</option><option :value="20">20 个片段</option></select><button class="btn primary full-width" :disabled="!retrievalQuery.trim() || retrieval.loading.value" @click="retrieval.load()"><Search :size="17"/>{{ retrieval.loading.value ? '检索中…' : '开始检索' }}</button><ErrorNotice :error="retrieval.error.value"/></div><div><div class="section-title"><h2>检索结果</h2><span class="count-pill">{{ retrieval.data.value?.hits?.length ?? 0 }}</span></div><p v-if="retrieval.data.value?.degraded" class="warning-notice">部分检索服务异常，当前命中可能不完整。</p><div v-if="retrieval.loading.value" class="skeleton-card"/><article v-for="(hit, i) in retrieval.data.value?.hits || []" :key="hit.chunk_id" class="panel retrieval-hit"><div class="hit-header"><span class="rank-number">{{ String(i + 1).padStart(2, '0') }}</span><strong>{{ locationLabel(hit.locator) }}</strong><span class="score">检索分数 {{ hit.fused_score?.toFixed(4) }}</span></div><p>{{ hit.display_text || hit.text }}</p><div class="hit-footer"><span v-for="channel in hit.channels" :key="channel" class="tag">{{ { dense: '语义召回', sparse: '关键词召回', bm25: '关键词召回' }[channel] || channel }}</span><RouterLink :to="`/knowledge-bases/${spaceId}/documents/${hit.document_id}?version=${hit.document_version_id}&chunk=${hit.chunk_id}`">查看文档<ArrowUpRight :size="14"/></RouterLink></div></article><EmptyState v-if="!retrieval.loading.value && !retrieval.data.value?.hits?.length" :title="retrieval.data.value ? '没有找到可用片段' : '等待第一次检索'" description="只有已发布且当前可用的内容参与检索。"/></div></section>
  <section v-else class="settings-layout"><form class="panel settings-panel" @submit.prevent="saveSettings"><h2>知识库信息</h2><p class="muted">一个清晰的名称与描述，让知识更容易被找到。</p><label class="field-label" for="settings-name">名称</label><input id="settings-name" v-model="settingsName" required maxlength="100"/><label class="field-label" for="settings-description">描述</label><textarea id="settings-description" v-model="settingsDescription" rows="4" maxlength="2000"/><div class="dialog-actions"><span v-if="settingsSaved" class="success-text small"><Check :size="15"/>已保存</span><button class="btn primary" :disabled="settingsBusy || !settingsName.trim()">{{ settingsBusy ? '保存中…' : '保存修改' }}</button></div></form><div class="panel settings-panel"><h2>处理方式</h2><dl class="info-list"><div><dt>发布流程</dt><dd>解析 → 质量复核 → 确认发布</dd></div><div><dt>检索方式</dt><dd>语义与关键词混合检索</dd></div><div><dt>运行配置</dt><dd>{{ store.capabilities?.profile === 'production' ? '真实服务' : '本地验证环境' }}</dd></div><div><dt>音频解析</dt><dd>尚未配置</dd></div></dl><p class="small muted">解析与模型参数沿用服务端配置。</p></div></section>
  <UploadDialog :open="uploading" :space-id="spaceId" @close="uploading = false; load()"/>
  <AppDialog :open="publishOpen" title="检查并确认发布" wide @close="!batchBusy && (publishOpen = false)"><p class="muted">仅对选中的待复核文档执行发布。发布前将再次读取质量报告，检查未通过的文档会跳过。</p><div v-for="row in publishTargets" :key="row.document_id" class="review-row"><FileText :size="18"/><span>{{ row.filename }}<small v-if="row.quality">{{ row.quality.node_count }} 个内容节点 · 来源位置覆盖 {{ Math.round(row.quality.locator_coverage * 100) }}% · {{ row.quality.disposition === 'BLOCKED_REAL_VALIDATION' ? '质量检查未通过' : '可人工复核' }}</small><small v-else>{{ qualityLoading ? '读取质量报告…' : '质量报告读取失败，本次跳过' }}</small><small v-if="row.quality?.issue_codes.length">有 {{ row.quality.issue_codes.length }} 项质量提示，请进入文档查看具体问题。</small></span><RouterLink :to="`/knowledge-bases/${spaceId}/documents/${row.document_id}`" class="text-button" @click="publishOpen = false">查看质量</RouterLink></div><div v-for="result in publishResults" :key="result.name" class="review-row"><span>{{ result.name }}</span><StatusBadge :value="result.success ? 'available' : 'inconsistent'"/><small v-if="result.detail">{{ result.detail }}</small></div><div class="dialog-actions"><button class="btn" :disabled="batchBusy" @click="publishOpen = false">关闭</button><button class="btn primary" :disabled="batchBusy || qualityLoading || !!publishResults.length || !publishTargets.some(r => r.quality && r.quality.disposition !== 'BLOCKED_REAL_VALIDATION')" @click="publishSelected">{{ batchBusy ? '发布中…' : '已检查质量，确认发布' }}</button></div></AppDialog>
</div></template>
