<script setup>
import { computed, ref, watch, onUnmounted } from 'vue';
import { ListTodo, RotateCw, ArrowUpRight, X, FileText, CircleCheck, Clock3, CircleAlert, LoaderCircle } from '@lucide/vue';
import { useWorkspace } from '../stores/workspace.js';
import { useUploads } from '../stores/uploads.js';
import { request, requestPage, queryString, jobCommand } from '../api.js';
import { useResource } from '../composables/useResource.js';
import { dateTime, processingLabels } from '../format.js';
import StatusBadge from '../components/StatusBadge.vue';
import ErrorNotice from '../components/ErrorNotice.vue';
import EmptyState from '../components/EmptyState.vue';
const workspace = useWorkspace(), uploads = useUploads();
const spaceId = ref(''), state = ref(''), rows = ref([]), cursor = ref(null), counts = ref({}), actionError = ref(null), busyIds = ref([]);
const resource = useResource(async signal => { const [page, summary] = await Promise.all([requestPage(`/ingestion-jobs?${queryString({ space_id: spaceId.value, state: state.value, limit: 30 })}`, { signal }), request(`/ingestion-jobs/summary?${queryString({ space_id: spaceId.value })}`, { signal })]); return { page, summary }; });
let revision = 0;
async function load() { const own = ++revision; const data = await resource.load(); if (data && own === revision) { rows.value = data.page.items; cursor.value = data.page.nextCursor; counts.value = data.summary.counts; } }
const moreLoading = ref(false);
async function more() { if (!cursor.value || moreLoading.value) return; const own = revision; moreLoading.value = true; try { const data = await requestPage(`/ingestion-jobs?${queryString({ space_id: spaceId.value, state: state.value, limit: 30, cursor: cursor.value })}`); if (own === revision) { rows.value.push(...data.items.filter(item => !rows.value.some(row => row.id === item.id))); cursor.value = data.nextCursor; } } catch (cause) { if (own === revision) actionError.value = cause; } finally { if (own === revision) moreLoading.value = false; } }
watch([spaceId, state], () => { rows.value = []; cursor.value = null; moreLoading.value = false; load(); }, { immediate: true });
const timer = setInterval(() => { if (!cursor.value && !moreLoading.value && !busyIds.value.length) load(); }, 6000);
onUnmounted(() => { ++revision; clearInterval(timer); });
async function execute(job, action) { busyIds.value.push(job.id); actionError.value = null; try { await jobCommand(job.id, action); await load(); } catch (cause) { actionError.value = cause; } finally { busyIds.value = busyIds.value.filter(id => id !== job.id); } }
const localRows = computed(() => uploads.items.filter(item => item.state !== 'submitted' && (!spaceId.value || item.spaceId === spaceId.value)));
const metrics = computed(() => [{ label: '等待处理', value: (counts.value.QUEUED || 0) + (counts.value.RETRY_WAIT || 0), icon: Clock3 }, { label: '正在处理', value: (counts.value.RUNNING || 0) + (counts.value.CANCEL_REQUESTED || 0), icon: LoaderCircle }, { label: '处理完成', value: counts.value.SUCCEEDED || 0, icon: CircleCheck }, { label: '处理失败', value: counts.value.FAILED_FINAL || 0, icon: CircleAlert }]);
const localLabels = { queued: '等待上传', hashing: '校验文件', uploading: '正在上传', completing: '提交处理中', failed: '上传失败', interrupted: '需要重新选择文件' };
</script>
<template><div class="page"><div class="page-heading"><div><p class="eyebrow">PROCESSING CENTER</p><h1>每一份知识，都有迹可循。</h1><p class="page-description">查看上传与解析任务，及时处理异常。</p></div><button class="btn" :disabled="resource.loading.value" @click="load"><RotateCw :size="17"/>刷新任务</button></div>
  <div class="metrics-grid"><div v-for="metric in metrics" :key="metric.label" class="metric-card"><div class="metric-top"><span>{{ metric.label }}</span><component :is="metric.icon" :size="18"/></div><div class="metric-number">{{ resource.loading.value && !rows.length ? '—' : metric.value }}</div><small>服务端当前保留的任务</small></div></div>
  <section v-if="localRows.length" class="panel local-tasks"><div class="section-title"><h2>本次上传</h2><span class="count-pill">{{ localRows.length }}</span></div><div v-for="item in localRows" :key="item.id" class="upload-row"><FileText :size="19"/><div class="grow"><strong>{{ item.filename }}</strong><p class="small muted">{{ localLabels[item.state] }}</p><progress v-if="['uploading','hashing'].includes(item.state)" :value="item.progress" max="1"/><p v-if="item.error" class="small danger-text">{{ item.error }}</p><p v-if="item.state === 'interrupted'" class="small muted">浏览器无法在刷新后恢复本地文件，请回到知识库重新选择。已提交的服务端任务见下方列表。</p></div><button v-if="item.state === 'failed' && item.file" class="btn small" @click="uploads.retry(item)">重试上传</button><RouterLink :to="`/knowledge-bases/${item.spaceId}/documents`" class="text-link">前往知识库<ArrowUpRight :size="14"/></RouterLink></div></section>
  <div class="section-toolbar"><div class="section-title"><h2>处理任务</h2></div><div class="toolbar-actions"><select v-model="spaceId" aria-label="按知识库筛选任务"><option value="">全部知识库</option><option v-for="space in workspace.spaces" :key="space.id" :value="space.id">{{ space.name }}</option></select><select v-model="state" aria-label="按任务状态筛选"><option value="">全部状态</option><option v-for="key in ['QUEUED','RUNNING','RETRY_WAIT','SUCCEEDED','FAILED_FINAL','CANCEL_REQUESTED','CANCELLED']" :key="key" :value="key">{{ processingLabels[key] }}</option></select></div></div>
  <ErrorNotice :error="resource.error.value" retry @retry="load"/><ErrorNotice :error="actionError"/>
  <div v-if="resource.loading.value && !rows.length" class="skeleton-card"/><EmptyState v-else-if="!rows.length && !resource.error.value" title="这里还没有处理任务" description="上传文件后，处理阶段与结果会同步显示在这里。"/>
  <div v-else class="task-list"><article v-for="job in rows" :key="job.id" class="task-card"><span class="file-symbol"><FileText :size="21"/></span><div class="task-main"><div class="task-title"><RouterLink :to="`/knowledge-bases/${job.space_id}/documents/${job.document_id}`">{{ job.filename }}</RouterLink><StatusBadge :status="job.state" kind="processing"/></div><p class="small muted">{{ workspace.spaces.find(s => s.id === job.space_id)?.name || '知识库记录不可用' }}<span class="separator">·</span>{{ dateTime(job.updated_at) }}<span class="separator">·</span>第 {{ job.attempt }} / {{ job.max_attempts }} 次处理</p><div class="task-stage"><span class="stage-dot" :class="{ running: ['RUNNING','QUEUED'].includes(job.state) }"/>{{ job.state === 'SUCCEEDED' ? '处理完成，前往文档检查质量与发布状态' : processingLabels[job.processing_state] || processingLabels[job.state] }}</div><details v-if="job.error_code" class="task-error"><summary>处理未完成，查看原因</summary><code>{{ job.error_code }}</code></details></div><div class="task-actions"><button v-if="job.available_actions.includes('retry')" class="btn" :disabled="busyIds.includes(job.id)" @click="execute(job, 'retry')"><RotateCw :size="15"/>重试</button><button v-if="job.available_actions.includes('cancel')" class="btn ghost" :disabled="busyIds.includes(job.id)" @click="execute(job, 'cancel')"><X :size="15"/>取消</button><RouterLink class="icon-button" :to="`/knowledge-bases/${job.space_id}/documents/${job.document_id}`" aria-label="查看任务文档"><ArrowUpRight :size="19"/></RouterLink></div></article></div><button v-if="cursor" class="btn load-more" :disabled="moreLoading" @click="more">{{ moreLoading ? '加载中…' : '加载更多任务' }}</button>
  <p class="footnote">任务来自持久化处理队列。完成和取消记录保留 7 天，失败记录保留 30 天；文档和版本记录继续保留。</p>
</div></template>
